// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

package main

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
)

// completionShells are the shells --completion writes a script for.
var completionShells = []string{"bash", "fish", "zsh"}

// pathFlags take a file path, so the shell completes file names for them.
var pathFlags = map[string]bool{"passmcp": true}

// option is one flag as a completion script lists it.
type option struct{ name, usage string }

// completionWriters render a completion script for one shell from the
// sorted flag list.
var completionWriters = map[string]func(b *strings.Builder, fs *flag.FlagSet, opts []option){
	"bash": bashCompletion,
	"zsh":  zshCompletion,
	"fish": fishCompletion,
}

// writeCompletion prints a completion script for shell, generated from the
// flag set itself, so a new flag completes without a second list to keep.
func writeCompletion(w io.Writer, fs *flag.FlagSet, shell string) error {
	render, ok := completionWriters[shell]
	if !ok {
		return fmt.Errorf("--completion takes one of %s, not %q", strings.Join(completionShells, ", "), shell)
	}
	var opts []option
	fs.VisitAll(func(f *flag.Flag) { opts = append(opts, option{f.Name, f.Usage}) })
	sort.Slice(opts, func(i, j int) bool { return opts[i].name < opts[j].name })

	var b strings.Builder
	render(&b, fs, opts)
	_, err := io.WriteString(w, b.String())
	return err
}

func bashCompletion(b *strings.Builder, _ *flag.FlagSet, opts []option) {
	var words []string
	for _, o := range opts {
		words = append(words, "--"+o.name)
	}
	fmt.Fprintf(b, "# bash completion for passmcp-server, generated by passmcp-server --completion bash\n")
	fmt.Fprintf(b, "_passmcp_server() {\n")
	fmt.Fprintf(b, "  local cur=\"${COMP_WORDS[COMP_CWORD]}\" prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	fmt.Fprintf(b, "  case \"$prev\" in\n")
	for _, o := range opts {
		if pathFlags[o.name] {
			fmt.Fprintf(b, "    --%s) COMPREPLY=($(compgen -f -- \"$cur\")); return ;;\n", o.name)
		}
	}
	fmt.Fprintf(b, "    --completion) COMPREPLY=($(compgen -W %q -- \"$cur\")); return ;;\n", strings.Join(completionShells, " "))
	fmt.Fprintf(b, "  esac\n")
	fmt.Fprintf(b, "  COMPREPLY=($(compgen -W %q -- \"$cur\"))\n", strings.Join(words, " "))
	fmt.Fprintf(b, "}\ncomplete -F _passmcp_server passmcp-server\n")
}

func zshCompletion(b *strings.Builder, fs *flag.FlagSet, opts []option) {
	fmt.Fprintf(b, "#compdef passmcp-server\n# zsh completion for passmcp-server, generated by passmcp-server --completion zsh\n_arguments \\\n")
	for _, o := range opts {
		fmt.Fprintf(b, "  '--%s[%s]%s' \\\n", o.name, zshEscape(o.usage), zshAction(fs, o.name))
	}
	fmt.Fprintf(b, "  && return 0\n")
}

// zshAction is what zsh completes after a flag: a path, a shell name, any
// value, or nothing for a boolean.
func zshAction(fs *flag.FlagSet, name string) string {
	switch {
	case pathFlags[name]:
		return ":path:_files"
	case name == "completion":
		return ":shell:(" + strings.Join(completionShells, " ") + ")"
	case !isBool(fs, name):
		return ":value: "
	}
	return ""
}

func fishCompletion(b *strings.Builder, fs *flag.FlagSet, opts []option) {
	fmt.Fprintf(b, "# fish completion for passmcp-server, generated by passmcp-server --completion fish\n")
	for _, o := range opts {
		fmt.Fprintf(b, "complete -c passmcp-server -l %s -d %q%s\n", o.name, o.usage, fishArgs(fs, o.name))
	}
}

// fishArgs are the extra `complete` options for a flag's value.
func fishArgs(fs *flag.FlagSet, name string) string {
	switch {
	case pathFlags[name]:
		return " -r -F"
	case name == "completion":
		return fmt.Sprintf(" -x -a %q", strings.Join(completionShells, " "))
	case !isBool(fs, name):
		return " -x"
	}
	return ""
}

func isBool(fs *flag.FlagSet, name string) bool {
	f := fs.Lookup(name)
	if f == nil {
		return false
	}
	b, ok := f.Value.(interface{ IsBoolFlag() bool })
	return ok && b.IsBoolFlag()
}

// zshEscape makes a usage string safe inside a single-quoted _arguments spec.
func zshEscape(s string) string {
	return strings.NewReplacer("'", "'\\''", "[", "\\[", "]", "\\]", ":", "\\:").Replace(s)
}
